<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>eIDGeregeDesktop.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\eIDGeregeDesktop.Application\eIDGeregeDesktop.Application.csproj" />
    <ProjectReference Include="..\eIDGeregeDesktop.Domain\eIDGeregeDesktop.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="QRCoder" />
  </ItemGroup>

</Project>
